# Site settings
title: Joe Greene's portfolio
email: jggreene@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your portfolio here!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://joegreene12.github.io" # the base hostname & protocol for your site
twitter_username: joegreene123
github_username:  joegreene12
linkedin_username: joegreene12

# Build settings
markdown: kramdown
